#!/bin/bash

# sudo ../src/ps-scanner-$1 -ni lo -ipd 127.0.0.1 -ips 10.0.0.2
sudo ../src/ps-scanner-$1 -ni lo -ipd 127.0.0.1 -pd 9999
# or (if you install `.deb`-package)
# sudo ps-scanner-$1 -ni lo -ipd $(hostname -I | awk '{print $1}') -pd 9999
