#!/bin/bash

# sudo ../src/ps-scanner-$1 -ni lo -ipd $(hostname -I | awk '{print $1}') -pd 9999
# or (if you install `.deb`-package)
sudo ps-scanner-$1 -ni lo -ipd $(hostname -I | awk '{print $1}') -pd 9999
